[package]
name = "synacor"
version = "0.1.0"
authors = ["Patrick Rogers <patrick@donotforget.xyz>"]
edition = "2018"

[dependencies]
byteorder = "1"

serde = { version = "1.0", features = ["derive"] }
bincode = "1"
serde-big-array = "0.1.4"